name = "ShipSnake"
short_name = "shipsnake"
author = "Cole Wilson"
email = "cole@colewilson.xyz"
short_description = "A quick and easy way to distribute your python projects!"
url = "https://github.com/cole-wilson/shipsnake"
license = "MIT"
keywords = "ship distribute package snake python freeze shipsnake setuptools"
data_files = [ "*.txt", "*.template",]
file = "main.py"
modules = [ "toml",]
description = "long_desc"

[build]
type = "1"
mac = "y"
windows = "y"
installer = "y"
ations = "y"
